export const DRIVER_SKILLSET = {
  corneringSpeed: 0,
  apexControl: 0,
  stabilityInTurns: 0,
  turnBraking: 0,
  reactionTime: 0,
  awareness: 0,
  evasiveManeuvers: 0,
  riskAssessment: 0,
  fuelManagement: 0,
  tyreManagement: 0,
  consistency: 0,
  errorProne: 0,
  aggressiveness: 0,
  defending: 0,
  overtaking: 0,
  starting: 0,
  carControl: 0,
  stamina: 0,
  rainPerformance: 0,
  carSetupKnowledge: 0,
};
