export const BIRTHPLACES: { [key: string]: string[] } = {
  de: [
    'Aachen',
    'Berlin',
    'Hamburg',
    'München',
    'Köln',
    'Frankfurt am Main',
    'Stuttgart',
    'Düsseldorf',
    'Dortmund',
    'Essen',
    'Leipzig',
    'Bremen',
    'Dresden',
    'Hannover',
    'Nürnberg',
    'Duisburg',
    'Bochum',
    'Wuppertal',
    'Bielefeld',
    'Bonn',
    'Mannheim',
    'Karlsruhe',
    'Wiesbaden',
    'Augsburg',
    'Mönchengladbach',
    'Gelsenkirchen',
    'Braunschweig',
    'Chemnitz',
    'Kiel',
    'Aachen',
    'Halle (Saale)',
    'Magdeburg',
    'Freiburg im Breisgau',
    'Krefeld',
    'Lübeck',
    'Oberhausen',
    'Erfurt',
    'Mainz',
    'Rostock',
    'Kassel',
    'Hagen',
  ],
  en: [
    'London',
    'Birmingham',
    'Manchester',
    'Liverpool',
    'Leeds',
    'Sheffield',
    'Bristol',
    'Newcastle',
    'Nottingham',
    'Leicester',
    'Glasgow',
    'Edinburgh',
    'Cardiff',
    'Coventry',
    'Hull',
    'Bradford',
    'Stoke-on-Trent',
    'Derby',
    'Sunderland',
    'Southampton',
    'Portsmouth',
    'Brighton',
    'Plymouth',
    'Wolverhampton',
    'Reading',
    'Aberdeen',
    'Dundee',
    'Luton',
    'Swindon',
    'Milton Keynes',
    'Northampton',
    'Warrington',
    'Oxford',
    'Cambridge',
    'Ipswich',
    'York',
    'Blackpool',
    'Preston',
    'Middlesbrough',
    'Southend-on-Sea',
  ],
  fr: [
    'Paris',
    'Marseille',
    'Lyon',
    'Toulouse',
    'Nice',
    'Nantes',
    'Strasbourg',
    'Montpellier',
    'Bordeaux',
    'Lille',
    'Rennes',
    'Reims',
    'Le Havre',
    'Saint-Étienne',
    'Toulon',
    'Grenoble',
    'Dijon',
    'Angers',
    'Nîmes',
    'Villeurbanne',
    'Clermont-Ferrand',
    'Aix-en-Provence',
    'Le Mans',
    'Brest',
    'Tours',
    'Amiens',
    'Limoges',
    'Annecy',
    'Perpignan',
    'Boulogne-Billancourt',
    'Metz',
    'Besançon',
    'Orléans',
    'Mulhouse',
    'Rouen',
    'Caen',
    'Nancy',
    'Saint-Denis',
    'Argenteuil',
  ],
  es: [
    'Madrid',
    'Barcelona',
    'Valencia',
    'Sevilla',
    'Zaragoza',
    'Málaga',
    'Murcia',
    'Palma de Mallorca',
    'Las Palmas de Gran Canaria',
    'Bilbao',
    'Alicante',
    'Córdoba',
    'Valladolid',
    'Vigo',
    'Gijón',
    'Eixample',
    'Hospitalet de Llobregat',
    'La Coruña',
    'Granada',
    'Vitoria-Gasteiz',
    'Elche',
    'Oviedo',
    'Santa Cruz de Tenerife',
    'Badalona',
    'Cartagena',
    'Terrassa',
    'Jerez de la Frontera',
    'Sabadell',
    'Móstoles',
    'Alcalá de Henares',
    'Pamplona',
    'Fuenlabrada',
    'Almería',
    'San Sebastián',
    'Leganés',
    'Burgos',
    'Santander',
    'Castellón de la Plana',
    'Getafe',
    'Albacete',
  ],
  it: [
    'Roma',
    'Milano',
    'Napoli',
    'Torino',
    'Palermo',
    'Genova',
    'Bologna',
    'Firenze',
    'Bari',
    'Catania',
    'Venezia',
    'Verona',
    'Messina',
    'Padova',
    'Trieste',
    'Taranto',
    'Brescia',
    'Prato',
    'Parma',
    'Modena',
    'Reggio Calabria',
    'Perugia',
    'Livorno',
    'Ravenna',
    'Cagliari',
    'Foggia',
    'Rimini',
    'Salerno',
    'Ferrara',
    'Sassari',
    'Latina',
    'Giugliano in Campania',
    'Monza',
    'Siracusa',
    'Pescara',
    'Bergamo',
    'Forlì',
    'Trento',
    'Vicenza',
    'Terni',
  ],
  sv: [
    'Stockholm',
    'Göteborg',
    'Malmö',
    'Uppsala',
    'Västerås',
    'Örebro',
    'Linköping',
    'Helsingborg',
    'Jönköping',
    'Norrköping',
    'Lund',
    'Umeå',
    'Gävle',
    'Borås',
    'Eskilstuna',
    'Södertälje',
    'Karlstad',
    'Täby',
    'Växjö',
    'Halmstad',
    'Sundsvall',
    'Luleå',
    'Trollhättan',
    'Östersund',
    'Borlänge',
    'Falun',
    'Kalmar',
    'Skellefteå',
    'Kristianstad',
    'Nyköping',
    'Karlskrona',
    'Mölndal',
    'Varberg',
    'Åkersberga',
    'Lidköping',
    'Alingsås',
    'Trelleborg',
    'Falkenberg',
    'Vänersborg',
  ],
  pl: [
    'Warszawa',
    'Kraków',
    'Łódź',
    'Wrocław',
    'Poznań',
    'Gdańsk',
    'Szczecin',
    'Bydgoszcz',
    'Lublin',
    'Katowice',
    'Białystok',
    'Gdynia',
    'Częstochowa',
    'Radom',
    'Sosnowiec',
    'Toruń',
    'Kielce',
    'Gliwice',
    'Zabrze',
    'Olsztyn',
    'Rzeszów',
    'Bielsko-Biała',
    'Ruda Śląska',
    'Rybnik',
    'Tychy',
    'Opole',
    'Elbląg',
    'Gorzów Wielkopolski',
    'Dąbrowa Górnicza',
    'Płock',
    'Wałbrzych',
    'Włocławek',
    'Tarnów',
    'Chorzów',
    'Zielona Góra',
    'Koszalin',
    'Legnica',
    'Grudziądz',
    'Słupsk',
    'Jaworzno',
    'Jastrzębie-Zdrój',
  ],
  zh: [
    'Beijing',
    'Shanghai',
    'Guangzhou',
    'Shenzhen',
    'Tianjin',
    'Chongqing',
    'Hangzhou',
    'Chengdu',
    'Nanjing',
    'Wuhan',
    "Xi'an",
    'Dongguan',
    'Foshan',
    'Shenyang',
    'Harbin',
    'Suzhou',
    'Qingdao',
    'Dalian',
    'Zhengzhou',
    'Jinan',
    'Changsha',
    'Kunming',
    'Ningbo',
    'Shijiazhuang',
    'Xiamen',
    'Wuxi',
    'Hefei',
    'Changchun',
    'Fuzhou',
    'Ürümqi',
    'Nanning',
    'Nanchang',
    'Guiyang',
    'Hohhot',
    'Lanzhou',
    'Yinchuan',
    'Haikou',
    'Zhuhai',
    'Zhongshan',
    'Taiyuan',
  ],
  jp: [
    'Tokyo',
    'Yokohama',
    'Osaka',
    'Nagoya',
    'Sapporo',
    'Fukuoka',
    'Kobe',
    'Kyoto',
    'Kawasaki',
    'Saitama',
    'Hiroshima',
    'Sendai',
    'Chiba',
    'Kitakyushu',
    'Sakai',
    'Niigata',
    'Hamamatsu',
    'Shizuoka',
    'Okayama',
    'Sagamihara',
    'Kumamoto',
    'Funabashi',
    'Kagoshima',
    'Hachioji',
    'Himeji',
    'Matsuyama',
    'Nagasaki',
    'Kawaguchi',
    'Yokosuka',
    'Gifu',
    'Fukuyama',
    'Oita',
    'Toyonaka',
    'Kanazawa',
    'Miyazaki',
    'Nagano',
    'Naha',
    'Takamatsu',
    'Kofu',
    'Fukushima',
    'Morioka',
  ],
  th: [
    'Bangkok',
    'Chiang Mai',
    'Phuket',
    'Pattaya',
    'Nakhon Ratchasima',
    'Hat Yai',
    'Udon Thani',
    'Khon Kaen',
    'Nakhon Si Thammarat',
    'Surat Thani',
    'Ubon Ratchathani',
    'Nonthaburi',
    'Samut Prakan',
    'Lampang',
    'Phitsanulok',
    'Songkhla',
    'Nakhon Pathom',
    'Ayutthaya',
    'Saraburi',
    'Rayong',
    'Trang',
    'Chiang Rai',
    'Sukhothai',
    'Kanchanaburi',
    'Lopburi',
    'Ratchaburi',
    'Mae Hong Son',
    'Tak',
    'Ranong',
    'Chachoengsao',
    'Phetchaburi',
    'Krabi',
    'Chumphon',
    'Yala',
    'Narathiwat',
    'Phetchabun',
    'Satun',
    'Uttaradit',
    'Prachuap Khiri Khan',
  ],
  sa: [
    'Riyadh',
    'Jeddah',
    'Mecca',
    'Medina',
    'Dammam',
    'Khobar',
    "Ta'if",
    'Tabuk',
    'Buraydah',
    'Al Khobar',
    'Khamis Mushait',
    'Hail',
    'Jizan',
    'Najran',
    'Al Hofuf',
    'Al Qatif',
    'Abha',
    'Al Jubail',
    'Yanbu',
    'Arar',
    'Sakakah',
    'Al Bahah',
    'Dhahran',
    'Al Mubarraz',
    'Al Kharj',
    'Unaizah',
    'Ras Tanura',
    'Al Qunfudhah',
    'Al Lith',
    'Al Duwadimi',
    'Turaif',
    'Sharurah',
    'Rabigh',
    'Baljurashi',
    'Al Bukayriyah',
    'Wadi ad-Dawasir',
    'Rafha',
    'AlUla',
    'Al Mahd',
    'Bisha',
  ],
  dz: [
    'Algiers',
    'Oran',
    'Constantine',
    'Annaba',
    'Blida',
    'Batna',
    'Djelfa',
    'Sétif',
    'Sidi Bel Abbès',
    'Biskra',
    'Tébessa',
    'El Oued',
    'Skikda',
    'Tlemcen',
    'Béjaïa',
    'Mostaganem',
    'Bouira',
    'Ghardaïa',
    'Médéa',
    'Jijel',
    'Mascara',
    'Laghouat',
    'Chlef',
    'Khenchela',
    'Bordj Bou Arréridj',
    'Aïn Beïda',
    'Tiaret',
    'Relizane',
    'Souk Ahras',
    'Saïda',
    'Guelma',
    'Ouargla',
    'Adrar',
    'Tindouf',
    'Illizi',
    'Timimoun',
    'Naâma',
    'El Bayadh',
    'Aïn Témouchent',
    'Tizi Ouzou',
    "M'sila",
  ],
  eg: [
    'Kairo',
    'Alexandria',
    'Gizeh',
    'Shubra El-Kheima',
    'Port Said',
    'Sues',
    'Luxor',
    'Mansura',
    'Tanta',
    'Ismailia',
    'Faiyum',
    'Asyut',
    'Zagazig',
    'Damietta',
    'Aswan',
    'Minya',
    'Beni Suef',
    'Qena',
    'Sohag',
    'Hurghada',
    '6th of October City',
    'Obour',
    'New Cairo',
    'Helwan',
    'Qalyub',
    'Banha',
    'Mahalla',
    'Damanhur',
    'Arish',
    'Basyun',
    'Marsa Matruh',
    'Belqas',
    'Edfu',
    'Idfu',
    'Kom Ombo',
    'Rosetta',
    'Burg El Arab',
    'Kharga',
    'El Gouna',
  ],
  za: [
    'Johannesburg',
    'Cape Town',
    'Durban',
    'Pretoria',
    'Port Elizabeth',
    'Bloemfontein',
    'Pietermaritzburg',
    'East London',
    'Nelspruit',
    'Polokwane',
    'Kimberley',
    'Rustenburg',
    'George',
    'Soweto',
    'Tshwane',
    'Welkom',
    'Newcastle',
    'Vanderbijlpark',
    'Secunda',
    'Witbank',
    'Klerksdorp',
    'Upington',
    'Grahamstown',
    'Mthatha',
    'Richards Bay',
    'Potchefstroom',
    'Krugersdorp',
    'Randburg',
    'Sasolburg',
    'Vereeniging',
    'Brits',
    'Bethlehem',
    'Middelburg',
    'Tzaneen',
    'Lichtenburg',
    'Stellenbosch',
    'Knysna',
    'Queenstown',
    'Thohoyandou',
    'Phalaborwa',
  ],
  na: [
    'Windhoek',
    'Walvis Bay',
    'Swakopmund',
    'Rundu',
    'Oshakati',
    'Rehoboth',
    'Otjiwarongo',
    'Okahandja',
    'Lüderitz',
    'Ondangwa',
    'Katima Mulilo',
    'Mariental',
    'Grootfontein',
    'Outjo',
    'Karibib',
    'Usakos',
    'Gobabis',
    'Keetmanshoop',
    'Tsumeb',
    'Henties Bay',
    'Karasburg',
    'Aranos',
    'Okakarara',
    'Ongwediva',
    'Omuthiya',
    'Eenhana',
    'Outapi',
    'Opuwo',
    'Nkurenkuru',
    'Kamanjab',
    'Oranjemund',
    'Bethanie',
    'Maltahöhe',
    'Khorixas',
    'Omaruru',
    'Otavi',
    'Okongo',
    'Oshikango',
    'Ruacana',
    'Kalkfeld',
  ],
  ma: [
    'Casablanca',
    'Rabat',
    'Fès',
    'Marrakesch',
    'Agadir',
    'Tanger',
    'Meknès',
    'Oujda',
    'Kenitra',
    'Tétouan',
    'Safi',
    'Mohammedia',
    'Khouribga',
    'Beni Mellal',
    'Nador',
    'Khemisset',
    'Ksar el-Kebir',
    'Larache',
    'Al Hoceima',
    'El Jadida',
    'Settat',
    'Sidi Kacem',
    'Essaouira',
    'Ouarzazate',
    'Errachidia',
    'Guercif',
    'Taourirt',
    'Sidi Slimane',
    'Tiznit',
    'Taroudant',
    'Ifrane',
    'Azrou',
    'Taza',
    'Midelt',
    'Sefrou',
    'Boujdour',
    'Asilah',
    'Zagora',
    'Boulemane',
    'Chefchaouen',
    'Dakhla',
  ],
  tr: [
    'Istanbul',
    'Ankara',
    'Izmir',
    'Bursa',
    'Antalya',
    'Adana',
    'Konya',
    'Gaziantep',
    'Mersin',
    'Kayseri',
    'Eskisehir',
    'Diyarbakir',
    'Samsun',
    'Denizli',
    'Şanlıurfa',
    'Malatya',
    'Kocaeli',
    'Manisa',
    'Kahramanmaraş',
    'Trabzon',
    'Elazığ',
    'Sivas',
    'Hatay',
    'Aydın',
    'Sakarya',
    'Tekirdağ',
    'Isparta',
    'Çanakkale',
    'Afyonkarahisar',
    'Balıkesir',
    'Batman',
    'Bolu',
    'Çorum',
    'Amasya',
    'Adıyaman',
    'Van',
    'Erzurum',
    'Muş',
    'Kütahya',
    'Bingöl',
  ],
  ar: [
    'Buenos Aires',
    'Córdoba',
    'Rosario',
    'Mendoza',
    'La Plata',
    'Mar del Plata',
    'San Miguel de Tucumán',
    'Salta',
    'Santa Fe',
    'San Juan',
    'Resistencia',
    'Neuquén',
    'Santiago del Estero',
    'Corrientes',
    'Bahía Blanca',
    'Posadas',
    'Paraná',
    'San Salvador de Jujuy',
    'Trelew',
    'Viedma',
    'Comodoro Rivadavia',
    'San Fernando del Valle de Catamarca',
    'Río Cuarto',
    'San Luis',
    'Formosa',
    'San Rafael',
    'Ushuaia',
    'Río Gallegos',
    'La Rioja',
    'Concordia',
    'Goya',
    'Puerto Madryn',
    'Villa María',
    'Santa Rosa',
    'Tandil',
    'Lomas de Zamora',
    'Lanús',
    'Banfield',
    'Quilmes',
    'Bahía Blanca',
  ],
  br: [
    'São Paulo',
    'Rio de Janeiro',
    'Brasília',
    'Salvador',
    'Fortaleza',
    'Belo Horizonte',
    'Curitiba',
    'Manaus',
    'Recife',
    'Porto Alegre',
    'Belém',
    'Goiânia',
    'Guarulhos',
    'Campinas',
    'São Luís',
    'São Gonçalo',
    'Maceió',
    'Duque de Caxias',
    'Natal',
    'Teresina',
    'Nova Iguaçu',
    'São Bernardo do Campo',
    'João Pessoa',
    'Santo André',
    'Ribeirão Preto',
    'Contagem',
    'Uberlândia',
    'Sorocaba',
    'Feira de Santana',
    'Aracaju',
    'Cuiabá',
    'Joinville',
    'Juiz de Fora',
    'Londrina',
    'Aparecida de Goiânia',
    'Ananindeua',
    'Niterói',
    'Belford Roxo',
    'Campos dos Goytacazes',
    'Serra',
  ],
  ca: [
    'Toronto',
    'Vancouver',
    'Montreal',
    'Calgary',
    'Ottawa',
    'Edmonton',
    'Quebec City',
    'Winnipeg',
    'Hamilton',
    'Kitchener',
    'London',
    'Victoria',
    'Halifax',
    'Saskatoon',
    'Regina',
    "St. John's",
    'Windsor',
    'Sudbury',
    'Oshawa',
    'Sherbrooke',
    'Barrie',
    'Guelph',
    'Kelowna',
    'Abbotsford',
    'Saguenay',
    'Trois-Rivières',
    'Moncton',
    'Saint John',
    'Thunder Bay',
    'Charlottetown',
    'Lethbridge',
    'Saint-Jérôme',
    'Chilliwack',
    'Red Deer',
    'Kamloops',
    'Prince George',
    'Brantford',
    'Nanaimo',
    'Peterborough',
    'Fredericton',
  ],
  co: [
    'Bogotá',
    'Medellín',
    'Cali',
    'Barranquilla',
    'Cartagena',
    'Cúcuta',
    'Bucaramanga',
    'Pereira',
    'Manizales',
    'Santa Marta',
    'Ibagué',
    'Villavicencio',
    'Montería',
    'Neiva',
    'Popayán',
    'Armenia',
    'Pasto',
    'Valledupar',
    'Sincelejo',
    'Riohacha',
    'Quibdó',
    'Florencia',
    'Tunja',
    'Yopal',
    'Leticia',
    'Mitú',
    'San Andrés',
    'Mocoa',
    'Ipiales',
    'Rionegro',
    'Sogamoso',
    'Facatativá',
    'Palmira',
    'Soacha',
    'Envigado',
    'Girardot',
    'Jamundí',
    'Tuluá',
    'Zipaquirá',
    'Chía',
  ],
  mx: [
    'Ciudad de México',
    'Guadalajara',
    'Monterrey',
    'Puebla',
    'Tijuana',
    'León',
    'Ciudad Juárez',
    'Zapopan',
    'Querétaro',
    'San Luis Potosí',
    'Mérida',
    'Aguascalientes',
    'Mexicali',
    'Cancún',
    'Toluca',
    'Chihuahua',
    'Hermosillo',
    'Morelia',
    'Saltillo',
    'Culiacán',
    'Veracruz',
    'Torreón',
    'Reynosa',
    'Tampico',
    'Tuxtla Gutiérrez',
    'Durango',
    'Xalapa',
    'Acapulco',
    'Villahermosa',
    'Tepic',
    'Irapuato',
    'Matamoros',
    'Celaya',
    'Ensenada',
    'Mazatlán',
    'La Paz',
    'Apodaca',
    'Tlalnepantla',
    'Chimalhuacán',
    'Tultepec',
  ],
  us: [
    'New York',
    'Los Angeles',
    'Chicago',
    'Houston',
    'Phoenix',
    'Philadelphia',
    'San Antonio',
    'San Diego',
    'Dallas',
    'San Jose',
    'Austin',
    'Jacksonville',
    'Fort Worth',
    'Columbus',
    'Charlotte',
    'San Francisco',
    'Indianapolis',
    'Seattle',
    'Denver',
    'Washington D.C.',
    'Boston',
    'El Paso',
    'Nashville',
    'Detroit',
    'Oklahoma City',
    'Portland',
    'Las Vegas',
    'Memphis',
    'Louisville',
    'Baltimore',
    'Milwaukee',
    'Albuquerque',
    'Tucson',
    'Fresno',
    'Sacramento',
    'Kansas City',
    'Atlanta',
    'Miami',
    'Raleigh',
    'Omaha',
  ],
  au: [
    'Sydney',
    'Melbourne',
    'Brisbane',
    'Perth',
    'Adelaide',
    'Gold Coast',
    'Canberra',
    'Newcastle',
    'Wollongong',
    'Logan City',
    'Geelong',
    'Hobart',
    'Townsville',
    'Cairns',
    'Darwin',
    'Toowoomba',
    'Ballarat',
    'Bendigo',
    'Launceston',
    'Mackay',
    'Rockhampton',
    'Bundaberg',
    'Bunbury',
    'Coffs Harbour',
    'Wagga Wagga',
    'Hervey Bay',
    'Mildura',
    'Shepparton',
    'Albury',
    'Port Macquarie',
    'Kalgoorlie',
    'Tamworth',
    'Orange',
    'Dubbo',
    'Geraldton',
    'Alice Springs',
    'Mount Gambier',
    'Gladstone',
    'Busselton',
    'Whyalla',
  ],
  ua: [
    'Kyiv',
    'Kharkiv',
    'Odesa',
    'Dnipro',
    'Donetsk',
    'Zaporizhzhia',
    'Lviv',
    'Kryvyi Rih',
    'Mykolaiv',
    'Mariupol',
    'Vinnytsia',
    'Kherson',
    'Poltava',
    'Chernihiv',
    'Cherkasy',
    'Zhytomyr',
    'Sumy',
    'Rivne',
    'Ivano-Frankivsk',
    'Kremenchuk',
    'Ternopil',
    'Lutsk',
    'Uzhhorod',
    'Bila Tserkva',
    'Melitopol',
    'Nikopol',
    'Sevastopol',
    'Kamianets-Podilskyi',
    'Kropyvnytskyi',
    'Khmelnitskyi',
    'Berdyansk',
    'Chernivtsi',
    'Brovary',
    'Pavlohrad',
    'Uman',
    'Kostopil',
    'Kolomyia',
    'Boryspil',
    'Mukachevo',
    'Sievierodonetsk',
  ],
  fi: [
    'Helsinki',
    'Espoo',
    'Tampere',
    'Vantaa',
    'Oulu',
    'Turku',
    'Jyväskylä',
    'Lahti',
    'Kuopio',
    'Pori',
    'Kouvola',
    'Joensuu',
    'Lappeenranta',
    'Vaasa',
    'Rovaniemi',
    'Seinäjoki',
    'Mikkeli',
    'Hämeenlinna',
    'Hyvinkää',
    'Porvoo',
    'Kokkola',
    'Lohja',
    'Kajaani',
    'Kemi',
    'Savonlinna',
    'Kerava',
    'Rauma',
    'Salo',
    'Kotka',
    'Raisio',
    'Nokia',
    'Rovaniemi',
    'Imatra',
    'Kouvola',
    'Järvenpää',
    'Pargas',
    'Kristiinankaupunki',
    'Loimaa',
    'Uusikaupunki',
    'Lapua',
  ],
  ao: [
    'Luanda',
    "N'dalatando",
    'Huambo',
    'Lobito',
    'Benguela',
    'Kuito',
    'Lubango',
    'Malanje',
    'Namibe',
    'Soyo',
    'Cabinda',
    'Uíge',
    'Saurimo',
    'Sumbe',
    'Menongue',
    'Caxito',
    'Ondjiva',
    'Luena',
    'Moçâmedes',
    'Mbanza Congo',
    'Catumbela',
    'Camacupa',
    'Longonjo',
    'Baia Farta',
    'Ambriz',
    'Cuito Cuanavale',
    'Chicala-Cholohanga',
    'Gabela',
    'Lucapa',
    'Nzeto',
    'Caluquembe',
    'Quibala',
    'Icolo e Bengo',
    'Cazenga',
    'Caála',
    'Viana',
    'Lumeje',
    'Cela',
    'Caconda',
    'Chitato',
    'Andulo',
  ],
  nz: [
    'Auckland',
    'Wellington',
    'Christchurch',
    'Hamilton',
    'Tauranga',
    'Dunedin',
    'Palmerston North',
    'Napier',
    'Hastings',
    'Nelson',
    'Rotorua',
    'New Plymouth',
    'Whangarei',
    'Invercargill',
    'Gisborne',
    'Porirua',
    'Upper Hutt',
    'Lower Hutt',
    'Masterton',
    'Levin',
    'Cambridge',
    'Taupo',
    'Timaru',
    'Ashburton',
    'Blenheim',
    'Whakatane',
    'Tokoroa',
    'Pukekohe',
    'Kerikeri',
    'Greymouth',
    'Waihi',
    'Oamaru',
    'Whitianga',
    'Queenstown',
    'Wanaka',
    'Te Awamutu',
    'Hokitika',
    'Warkworth',
    'Kaikoura',
    'Alexandra',
    'Balclutha',
  ],
  is: [
    'Reykjavík',
    'Kópavogur',
    'Hafnarfjörður',
    'Akureyri',
    'Reykjanesbær',
    'Garðabær',
    'Mosfellsbær',
    'Árborg',
    'Fjarðabyggð',
    'Akranes',
    'Selfoss',
    'Vestmannaeyjar',
    'Egilsstaðir',
    'Borgarnes',
    'Húsavík',
    'Grindavík',
    'Sauðárkrókur',
    'Hveragerði',
    'Ísafjörður',
    'Bolungarvík',
    'Siglufjörður',
    'Vík í Mýrdal',
    'Neskaupstaður',
    'Blönduós',
    'Egilsstaðir',
    'Seyðisfjörður',
    'Höfn',
    'Stykkishólmur',
    'Eskifjörður',
    'Vopnafjörður',
    'Þorlákshöfn',
    'Dalvík',
    'Patreksfjörður',
    'Flúðir',
    'Hólmavík',
    'Hvammstangi',
    'Skagaströnd',
    'Keflavík',
    'Ólafsvík',
    'Mývatn',
  ],
  ch: [
    'Zürich',
    'Genf',
    'Basel',
    'Lausanne',
    'Bern',
    'Winterthur',
    'Luzern',
    'St. Gallen',
    'Lugano',
    'Biel',
    'Thun',
    'Köniz',
    'La Chaux-de-Fonds',
    'Fribourg',
    'Schaffhausen',
    'Vernier',
    'Sion',
    'Emmen',
    'Neuchâtel',
    'Zug',
    'Uster',
    'Chur',
    'Lancy',
    'Yverdon-les-Bains',
    'Rapperswil-Jona',
    'Montreux',
    'Dietikon',
    'Frauenfeld',
    'Wetzikon',
    'Baden',
    'Dübendorf',
    'Grenchen',
    'Wil',
    'Bulle',
    'Kreuzlingen',
    'Pully',
    'Meyrin',
    'Aarau',
    'Carouge',
    'Wettingen',
    'Vevey',
  ],
  at: [
    'Wien',
    'Graz',
    'Linz',
    'Salzburg',
    'Innsbruck',
    'Klagenfurt',
    'Villach',
    'Wels',
    'St. Pölten',
    'Dornbirn',
    'Wiener Neustadt',
    'Steyr',
    'Feldkirch',
    'Bregenz',
    'Leonding',
    'Klosterneuburg',
    'Baden',
    'Wolfsberg',
    'Leoben',
    'Krems',
    'Traun',
    'Amstetten',
    'Lustenau',
    'Kapfenberg',
    'Mödling',
    'Hallein',
    'Kufstein',
    'Schwechat',
    'Tulln',
    'Hohenems',
    'Perchtoldsdorf',
    'Lienz',
    'Stockerau',
    'Knittelfeld',
    'Bischofshofen',
    'Seekirchen',
    'Vöcklabruck',
    'Enns',
    'Gmunden',
    'Bludenz',
  ],
  pt: [
    'Lisboa',
    'Porto',
    'Amadora',
    'Braga',
    'Coimbra',
    'Funchal',
    'Aveiro',
    'Setúbal',
    'Queluz',
    'Cacém',
    'Vila Nova de Gaia',
    'Odivelas',
    'Leiria',
    'Barreiro',
    'Ponta Delgada',
    'Matosinhos',
    'Gondomar',
    'Guimarães',
    'Rio Tinto',
    'Cascais',
    'Maia',
    'Beja',
    'Évora',
    'Faro',
    'Viseu',
    'Viana do Castelo',
    'Torres Vedras',
    'Olhão',
    'Castelo Branco',
    'Sesimbra',
    'Loulé',
    'Figueira da Foz',
    'Almada',
    'Montijo',
    'Póvoa de Varzim',
    'Peniche',
    'Bragança',
    'Santarém',
    'Vila Real',
    'Tomar',
  ],
  no: [
    'Oslo',
    'Bergen',
    'Trondheim',
    'Stavanger',
    'Drammen',
    'Fredrikstad',
    'Kristiansand',
    'Tromsø',
    'Sandnes',
    'Skien',
    'Ålesund',
    'Tønsberg',
    'Moss',
    'Haugesund',
    'Arendal',
    'Bodø',
    'Hamar',
    'Larvik',
    'Halden',
    'Kongsberg',
    'Molde',
    'Lillehammer',
    'Steinkjer',
    'Gjøvik',
    'Harstad',
    'Narvik',
    'Alta',
    'Elverum',
    'Grimstad',
    'Egersund',
    'Kongsvinger',
    'Voss',
    'Kristiansund',
    'Svolvær',
    'Fauske',
    'Risør',
    'Mo i Rana',
    'Røros',
    'Volda',
    'Flekkefjord',
  ],
  lv: [
    'Rīga',
    'Daugavpils',
    'Liepāja',
    'Jelgava',
    'Jūrmala',
    'Ventspils',
    'Rēzekne',
    'Valmiera',
    'Ogre',
    'Cēsis',
    'Salaspils',
    'Kuldīga',
    'Tukums',
    'Bauska',
    'Saldus',
    'Sigulda',
    'Līvāni',
    'Ludza',
    'Madona',
    'Dobele',
    'Aizkraukle',
    'Limbaži',
    'Smiltene',
    'Talsi',
    'Preiļi',
    'Balvi',
    'Aloja',
    'Kandava',
    'Alūksne',
    'Gulbene',
    'Olaine',
    'Plavinas',
    'Skrunda',
    'Rundale',
    'Grobiņa',
    'Dagda',
    'Viesīte',
    'Jēkabpils',
    'Valka',
    'Sabile',
  ],
  ro: [
    'București',
    'Cluj-Napoca',
    'Timișoara',
    'Iași',
    'Constanța',
    'Craiova',
    'Brașov',
    'Galați',
    'Ploiești',
    'Oradea',
    'Brăila',
    'Arad',
    'Pitești',
    'Sibiu',
    'Bacău',
    'Târgu Mureș',
    'Baia Mare',
    'Buzău',
    'Botoșani',
    'Satu Mare',
    'Râmnicu Vâlcea',
    'Suceava',
    'Focșani',
    'Vaslui',
    'Tulcea',
    'Târgu Jiu',
    'Reșița',
    'Piatra Neamț',
    'Drobeta-Turnu Severin',
    'Slatina',
    'Alba Iulia',
    'Deva',
    'Zalău',
    'Hunedoara',
    'Giurgiu',
    'Bistrița',
    'Călărași',
    'Alexandria',
    'Sfântu Gheorghe',
    'Făgăraș',
    'Roman',
  ],
  in: [
    'Mumbai',
    'Delhi',
    'Bangalore',
    'Hyderabad',
    'Ahmedabad',
    'Chennai',
    'Kolkata',
    'Surat',
    'Pune',
    'Jaipur',
    'Lucknow',
    'Kanpur',
    'Nagpur',
    'Indore',
    'Thane',
    'Bhopal',
    'Visakhapatnam',
    'Patna',
    'Vadodara',
    'Ghaziabad',
    'Ludhiana',
    'Agra',
    'Nashik',
    'Faridabad',
    'Meerut',
    'Rajkot',
    'Kalyan',
    'Vasai-Virar',
    'Varanasi',
    'Srinagar',
    'Aurangabad',
    'Dhanbad',
    'Amritsar',
    'Navi Mumbai',
    'Allahabad',
    'Howrah',
    'Ranchi',
    'Gwalior',
    'Jabalpur',
    'Coimbatore',
    'Vijayawada',
  ],
  gr: [
    'Athen',
    'Thessaloniki',
    'Patras',
    'Heraklion',
    'Larisa',
    'Volos',
    'Rhodos',
    'Ioannina',
    'Chania',
    'Kavala',
    'Alexandroupoli',
    'Katerini',
    'Lamia',
    'Komotini',
    'Agrinio',
    'Kalamata',
    'Trikala',
    'Serres',
    'Xanthi',
    'Veria',
    'Drama',
    'Karditsa',
    'Chalkida',
    'Ptolemaida',
    'Kastoria',
    'Giannitsa',
    'Corfu',
    'Sparti',
    'Mytilene',
    'Rethymno',
    'Samos',
    'Kos',
    'Argos',
    'Elefsina',
    'Thebes',
    'Livadeia',
    'Edessa',
    'Kilkis',
    'Messolonghi',
    'Naousa',
    'Orestiada',
  ],
  kr: [
    'Seoul',
    'Busan',
    'Incheon',
    'Daegu',
    'Daejeon',
    'Gwangju',
    'Suwon',
    'Ulsan',
    'Changwon',
    'Seongnam',
    'Goyang',
    'Yongin',
    'Bucheon',
    'Ansan',
    'Cheongju',
    'Jeonju',
    'Anyang',
    'Uijeongbu',
    'Pohang',
    'Jeju',
    'Cheonan',
    'Gimhae',
    'Hwaseong',
    'Namyangju',
    'Siheung',
    'Gumi',
    'Pyeongtaek',
    'Jinju',
    'Masan',
    'Wonju',
    'Gangneung',
    'Chuncheon',
    'Gunsan',
    'Seosan',
    'Iksan',
    'Gwangmyeong',
    'Asan',
    'Osan',
    'Anseong',
    'Gimpo',
  ],
  vn: [
    'Ho Chi Minh City',
    'Hanoi',
    'Da Nang',
    'Hai Phong',
    'Can Tho',
    'Bien Hoa',
    'Nha Trang',
    'Hue',
    'Vung Tau',
    'Rach Gia',
    'Quy Nhon',
    'Long Xuyen',
    'Thanh Hoa',
    'Thai Nguyen',
    'Nam Dinh',
    'Ha Long',
    'Phan Thiet',
    'Tam Ky',
    'Vinh',
    'Bac Ninh',
    'Ha Tinh',
    'Ca Mau',
    'Hoa Binh',
    'Tuy Hoa',
    'Dong Hoi',
    'Soc Trang',
    'Lao Cai',
    'My Tho',
    'Pleiku',
    'Ha Giang',
    'Tay Ninh',
    'Dong Ha',
    'Buon Ma Thuot',
    'Lai Chau',
    'Bac Giang',
    'Phu Yen',
    'Mong Cai',
    'Son La',
    'Sa Dec',
    'Tan An',
    'Phu Ly',
  ],
  sc: [
    'Glasgow',
    'Edinburgh',
    'Aberdeen',
    'Dundee',
    'Inverness',
    'Stirling',
    'Perth',
    'Paisley',
    'East Kilbride',
    'Livingston',
    'Cumbernauld',
    'Hamilton',
    'Kilmarnock',
    'Dumfries',
    'Kirkcaldy',
    'Dunfermline',
    'Ayr',
    'Falkirk',
    'Greenock',
    'Coatbridge',
    'Motherwell',
    'Rutherglen',
    'Inverurie',
    'Elgin',
    'Dumbarton',
    'St Andrews',
    'Forfar',
    'Oban',
    'Arbroath',
    'Dornoch',
    'Fort William',
    'Lanark',
    'Montrose',
    'Stonehaven',
    'Peterhead',
    'Largs',
    'Newton Mearns',
    'Troon',
    'Irvine',
    'Campbeltown',
  ],
  ie: [
    'Dublin',
    'Cork',
    'Limerick',
    'Galway',
    'Waterford',
    'Drogheda',
    'Swords',
    'Dundalk',
    'Bray',
    'Navan',
    'Ennis',
    'Kilkenny',
    'Tralee',
    'Carlow',
    'Newbridge',
    'Balbriggan',
    'Naas',
    'Athlone',
    'Portlaoise',
    'Mullingar',
    'Wexford',
    'Greystones',
    'Clonmel',
    'Celbridge',
    'Tullamore',
    'Maynooth',
    'Killarney',
    'Leixlip',
    'Malahide',
    'Cobh',
    'Arklow',
    'Shannon',
    'Skerries',
    'Castlebar',
    'Mallow',
    'Longford',
    'Dunboyne',
    'Dingle',
    'Carrick-on-Shannon',
    'Westport',
  ],
};
