export const HAIR_COLORS = {
  male: {
    blonde: 13,
    brown: 40,
    black: 30,
    red: 4,
    gray: 7,
    white: 3,
    auburn: 3,
    darkBrown: 25,
    lightBrown: 10,
    strawberryBlonde: 2,
    platinumBlonde: 1,
    dirtyBlonde: 5,
    ashBlonde: 3,
    chestnut: 4,
    silver: 2,
    blue: 0.2,
    green: 0.1,
    pink: 0.05,
    purple: 0.05,
    pastel: 0.05,
    rainbow: 0.02,
  },

  female: {
    blonde: 17,
    brown: 35,
    black: 22,
    red: 6,
    gray: 5,
    white: 2,
    auburn: 5,
    darkBrown: 18,
    lightBrown: 12,
    strawberryBlonde: 4,
    platinumBlonde: 3,
    dirtyBlonde: 6,
    ashBlonde: 5,
    chestnut: 7,
    silver: 1,
    blue: 1,
    green: 0.5,
    pink: 0.4,
    purple: 0.4,
    pastel: 0.2,
    rainbow: 0.1,
  },
};
