export const NATIONALITIES = {
  de: {
    country: 'Germany',
    alternateSources: ['at', 'ch'],
    nameSourceChance: 20,
    ethnicOrigin: { white: 85, black: 5, asian: 4, mixed: 6 },
    genderDistribution: { male: 49, female: 51 },
  },
  en: {
    country: 'England',
    alternateSources: ['us', 'au', 'ca'],
    nameSourceChance: 15,
    ethnicOrigin: { white: 82, black: 7, asian: 6, mixed: 5 },
    genderDistribution: { male: 49, female: 51 },
  },
  fr: {
    country: 'France',
    alternateSources: ['ch', 'ca'],
    nameSourceChance: 20,
    ethnicOrigin: { white: 80, black: 10, asian: 3, mixed: 7 },
    genderDistribution: { male: 49, female: 51 },
  },
  es: {
    country: 'Spain',
    alternateSources: ['ar', 'mx', 'co'],
    nameSourceChance: 20,
    ethnicOrigin: { white: 70, black: 2, asian: 2, mixed: 26 },
    genderDistribution: { male: 49, female: 51 },
  },
  it: {
    country: 'Italy',
    alternateSources: ['ch'],
    nameSourceChance: 15,
    ethnicOrigin: { white: 85, black: 4, asian: 3, mixed: 8 },
    genderDistribution: { male: 48, female: 52 },
  },
  sv: {
    country: 'Sweden',
    alternateSources: ['fi', 'no'],
    nameSourceChance: 10,
    ethnicOrigin: { white: 85, black: 3, asian: 6, mixed: 6 },
    genderDistribution: { male: 49, female: 51 },
  },
  pl: {
    country: 'Poland',
    alternateSources: [],
    nameSourceChance: 0,
    ethnicOrigin: { white: 97, black: 1, asian: 1, mixed: 1 },
    genderDistribution: { male: 48, female: 52 },
  },
  zh: {
    country: 'China',
    alternateSources: [],
    nameSourceChance: 0,
    ethnicOrigin: { asian: 99, white: 1 },
    genderDistribution: { male: 51, female: 49 },
  },
  jp: {
    country: 'Japan',
    alternateSources: [],
    nameSourceChance: 0,
    ethnicOrigin: { asian: 99, white: 1 },
    genderDistribution: { male: 51, female: 49 },
  },
  th: {
    country: 'Thailand',
    alternateSources: ['vn'],
    nameSourceChance: 0,
    ethnicOrigin: { asian: 99, white: 1 },
    genderDistribution: { male: 51, female: 49 },
  },
  sa: {
    country: 'Saudi Arabia',
    alternateSources: [],
    nameSourceChance: 0,
    ethnicOrigin: { arab: 98, black: 2 },
    genderDistribution: { male: 52, female: 48 },
  },
  dz: {
    country: 'Algeria',
    alternateSources: ['ma', 'eg'],
    nameSourceChance: 15,
    ethnicOrigin: { arab: 90, black: 5, mixed: 5 },
    genderDistribution: { male: 51, female: 49 },
  },
  eg: {
    country: 'Egypt',
    alternateSources: ['dz', 'sa'],
    nameSourceChance: 10,
    ethnicOrigin: { arab: 94, black: 4, mixed: 2 },
    genderDistribution: { male: 51, female: 49 },
  },
  za: {
    country: 'South Africa',
    alternateSources: ['na'],
    nameSourceChance: 15,
    ethnicOrigin: { black: 80, white: 8, asian: 2, mixed: 10 },
    genderDistribution: { male: 49, female: 51 },
  },
  na: {
    country: 'Namibia',
    alternateSources: ['za'],
    nameSourceChance: 10,
    ethnicOrigin: { black: 85, white: 10, mixed: 5 },
    genderDistribution: { male: 50, female: 50 },
  },
  ma: {
    country: 'Morocco',
    alternateSources: ['dz', 'eg'],
    nameSourceChance: 10,
    ethnicOrigin: { arab: 90, black: 6, mixed: 4 },
    genderDistribution: { male: 51, female: 49 },
  },
  tr: {
    country: 'Turkey',
    alternateSources: [],
    nameSourceChance: 0,
    ethnicOrigin: { white: 85, mixed: 15 },
    genderDistribution: { male: 50, female: 50 },
  },
  ar: {
    country: 'Argentina',
    alternateSources: ['es'],
    nameSourceChance: 20,
    ethnicOrigin: { white: 80, black: 3, mixed: 17 },
    genderDistribution: { male: 49, female: 51 },
  },
  br: {
    country: 'Brazil',
    alternateSources: [],
    nameSourceChance: 0,
    ethnicOrigin: { white: 47, black: 9, mixed: 44 },
    genderDistribution: { male: 49, female: 51 },
  },
  ca: {
    country: 'Canada',
    alternateSources: ['us', 'fr', 'en'],
    nameSourceChance: 15,
    ethnicOrigin: { white: 75, black: 10, asian: 10, mixed: 5 },
    genderDistribution: { male: 49, female: 51 },
  },
  co: {
    country: 'Colombia',
    alternateSources: ['es', 'mx'],
    nameSourceChance: 10,
    ethnicOrigin: { white: 65, black: 10, mixed: 25 },
    genderDistribution: { male: 50, female: 50 },
  },
  mx: {
    country: 'Mexico',
    alternateSources: ['es', 'ar'],
    nameSourceChance: 20,
    ethnicOrigin: { white: 67, black: 1, mixed: 32 },
    genderDistribution: { male: 50, female: 50 },
  },
  us: {
    country: 'United States',
    alternateSources: ['ca', 'en', 'au'],
    nameSourceChance: 15,
    ethnicOrigin: { white: 60, black: 13, asian: 6, mixed: 21 },
    genderDistribution: { male: 49, female: 51 },
  },
  au: {
    country: 'Australia',
    alternateSources: ['us', 'en'],
    nameSourceChance: 10,
    ethnicOrigin: { white: 76, asian: 10, black: 2, mixed: 12 },
    genderDistribution: { male: 49, female: 51 },
  },
  ua: {
    country: 'Ukraine',
    alternateSources: [],
    nameSourceChance: 0,
    ethnicOrigin: { white: 98, asian: 1, mixed: 1 },
    genderDistribution: { male: 46, female: 54 },
  },
  fi: {
    country: 'Finland',
    alternateSources: ['sv'],
    nameSourceChance: 10,
    ethnicOrigin: { white: 97, black: 1, asian: 1, mixed: 1 },
    genderDistribution: { male: 49, female: 51 },
  },
  ao: {
    country: 'Angola',
    alternateSources: [],
    nameSourceChance: 0,
    ethnicOrigin: { black: 98, white: 1, mixed: 1 },
    genderDistribution: { male: 50, female: 50 },
  },
  nz: {
    country: 'New Zealand',
    alternateSources: ['au', 'en'],
    nameSourceChance: 15,
    ethnicOrigin: { white: 70, asian: 15, mixed: 10, black: 5 },
    genderDistribution: { male: 49, female: 51 },
  },
  is: {
    country: 'Iceland',
    alternateSources: [],
    nameSourceChance: 0,
    ethnicOrigin: { white: 98, asian: 1, mixed: 1 },
    genderDistribution: { male: 50, female: 50 },
  },
  ch: {
    country: 'Switzerland',
    alternateSources: ['fr', 'de', 'it'],
    nameSourceChance: 20,
    ethnicOrigin: { white: 85, black: 5, asian: 5, mixed: 5 },
    genderDistribution: { male: 49, female: 51 },
  },
  at: {
    country: 'Austria',
    alternateSources: ['de', 'ch'],
    nameSourceChance: 15,
    ethnicOrigin: { white: 90, black: 3, asian: 3, mixed: 4 },
    genderDistribution: { male: 49, female: 51 },
  },
  pt: {
    country: 'Portugal',
    alternateSources: ['br'],
    nameSourceChance: 20,
    ethnicOrigin: { white: 85, black: 5, mixed: 10 },
    genderDistribution: { male: 49, female: 51 },
  },
  no: {
    country: 'Norway',
    alternateSources: ['sv'],
    nameSourceChance: 10,
    ethnicOrigin: { white: 90, black: 3, asian: 5, mixed: 2 },
    genderDistribution: { male: 50, female: 50 },
  },
  lv: {
    country: 'Latvia',
    alternateSources: [],
    nameSourceChance: 0,
    ethnicOrigin: { white: 97, asian: 1, mixed: 2 },
    genderDistribution: { male: 48, female: 52 },
  },
  ro: {
    country: 'Romania',
    alternateSources: [],
    nameSourceChance: 0,
    ethnicOrigin: { white: 96, black: 1, asian: 1, mixed: 2 },
    genderDistribution: { male: 49, female: 51 },
  },
  in: {
    country: 'India',
    alternateSources: [],
    nameSourceChance: 0,
    ethnicOrigin: { asian: 95, white: 1, mixed: 4 },
    genderDistribution: { male: 51, female: 49 },
  },
  gr: {
    country: 'Greece',
    alternateSources: [],
    nameSourceChance: 0,
    ethnicOrigin: { white: 98, black: 1, mixed: 1 },
    genderDistribution: { male: 49, female: 51 },
  },
  kr: {
    country: 'South Korea',
    alternateSources: [],
    nameSourceChance: 0,
    ethnicOrigin: { asian: 99, white: 1 },
    genderDistribution: { male: 51, female: 49 },
  },
  vn: {
    country: 'Vietnam',
    alternateSources: [],
    nameSourceChance: 0,
    ethnicOrigin: { asian: 99, white: 1 },
    genderDistribution: { male: 51, female: 49 },
  },
  sc: {
    country: 'Scotland',
    alternateSources: ['en', 'ie'],
    nameSourceChance: 10,
    ethnicOrigin: { white: 96, black: 2, asian: 1, mixed: 1 },
    genderDistribution: { male: 49, female: 51 },
  },
  ie: {
    country: 'Ireland',
    alternateSources: ['sc', 'en'],
    nameSourceChance: 10,
    ethnicOrigin: { white: 96, black: 1, asian: 2, mixed: 1 },
    genderDistribution: { male: 49, female: 51 },
  },
};
