export enum RepositoryKey {
  localization = 'LOC_REPOSITORY',
  session = 'SESSION_REPOSITORY',
  passwordReset = 'PASSWORDRESET_REPOSITORY',
  user = 'USER_REPOSITORY',
  message = 'MESSAGE_REPOSITORY',
  migration = 'MIGRATION_REPOSITORY',
  project = 'PROJECT_REPOSITORY',
  projectMember = 'PROJECTMEMBER_REPOSITORY',
  contentEntry = 'CONTENTENTRY_REPOSITORY',
  contentSchema = 'CONTENTSCHEMA_REPOSITORY',
  contentVersion = 'CONTENTVERSION_REPOSITORY',
  contentValue = 'CONTENTVALUE_REPOSITORY',
  asset = 'ASSET_REPOSITORY',
  userInvite = 'USERINVITE_REPOSITORY',
  apiToken = 'APITOKEN_REPOSITORY',
}
